/**
 * Organization Types
 * MULTI-TENANCY: Represents a customer organization/business account
 */

import type { SubscriptionTierName } from "./subscriptionTier";

export type Organization = {
  id: string; // Tenant ID (auto-generated by Firestore)
  name: string;
  owner_uid: string; // Firebase Auth UID of the owner
  
  // Subscription & Billing
  subscription_tier: SubscriptionTierName; // "free" | "starter" | "professional" | "enterprise"
  subscription_status: "active" | "trial" | "canceled" | "paused";
  
  // Usage counters (for enforcing tier limits)
  current_branch_count: number; // How many branches currently exist
  current_user_count: number; // ALL users (active + invited + inactive) count
  current_admin_count: number; // How many admins
  
  // Stripe billing (empty for FREE tier)
  stripe_customer_id?: string;
  stripe_subscription_id?: string;
  billing_email?: string;
  billing_period_start?: Date;
  billing_period_end?: Date;
  
  // Metadata
  created_at: Date;
  created_by: string; // owner_uid
  updated_at?: Date;
};

/**
 * Tenant: User's view of an organization they belong to
 * Used in auth context and UI for tenant switching
 */
export type Tenant = {
  id: string; // Organization ID
  name: string;
  role: "owner" | "admin" | "user"; // User's global role within this organization
  subscription_tier: SubscriptionTierName; // Tells UI what features are available
};

/**
 * Settings: Organization-wide settings (working hours, blocked slots, etc.)
 * MULTI-TENANCY: Each calendar has isolated settings
 * ID format: {orgId}_{calendarId}
 */
export type Settings = {
  id: string;
  org_id: string; // MULTI-TENANCY: Identifies which organization owns these settings
  calendar_id: string; // MULTI-TENANCY: Identifies which calendar these settings apply to
  
  working_hours?: {
    [day: string]: {
      startTime: string;
      endTime: string;
      enabled: boolean;
    };
  };
  working_days?: string[]; // e.g., ["Monday", "Tuesday", "Wednesday", "Thursday", "Friday"]
  
  blocked_slots?: Array<{
    _key: string;
    startTime: string;
    endTime: string;
    label: string;
  }>;
  
  calendar_integration?: {
    google?: {
      connected: boolean;
      calendar_id?: string;
      sync_enabled: boolean;
    };
    outlook?: {
      connected: boolean;
      calendar_id?: string;
      sync_enabled: boolean;
    };
  };
  
  restaurants?: {
    city: string;
    perimeter_km: number;
    list: Array<{
      name: string;
      address: string;
      lat: number;
      lng: number;
      website?: string;
    }>;
  };
};
